package com.blockchaintp.sawtooth.daml.rpc.exception;

/**
 * A Sawtooth writer service exception handler to unify exceptions generated by
 * dependencies such as those generated by sawtooth-java-sdk.
 */
public class SawtoothWriteServiceException extends Exception {

  private static final long serialVersionUID = 3437463937090384297L;

  /**
   * Construct exception from a throwable exception.
   *
   * @param throwable exception.
   */
  public SawtoothWriteServiceException(final Throwable throwable) {
    super(throwable);
  }

  /**
   * Construct exception from a message and a throwable exception.
   *
   * @param message describing the nature of the exception.
   * @param throwable exception.
   */
  public SawtoothWriteServiceException(final  String message, final Throwable throwable) {
    super(message, throwable);
  }

  /**
   * Construct an undefined exception class.
   */
  public SawtoothWriteServiceException() {
    super("Sawtooth writer service: Undefined Exception");
  }

  /**
   * Construct an exception class with a defined message.
   *
   * @param message to be displayed.
   */
  public SawtoothWriteServiceException(final String message) {
    super(String.format("Sawtooth writer service", message));
  }
 
}
