package com.blockchaintp.utils;

import sawtooth.sdk.signing.PrivateKey;
import sawtooth.sdk.signing.PublicKey;

/**
 * An interface to represent an identity.
 */
public interface KeyManager {

  /**
   * An accessor to a private key generated this manager.
   *
   * @return PrivateKey.
   */
  PrivateKey getPrivateKey();

  /**
   * An accessor to a public key generated by this manager.
   *
   * @return PublicKey.
   */
  PublicKey getPublicKey();

  /**
   * An accessor to the hex value of the public key generated by this manager.
   *
   * @return String representation of the hex value of public key.
   */
  String getPublicKeyInHex();

  /**
   * A signing method.
   *
   * @param item to be signed.
   * @return String representation of signed item.
   */
  String sign(byte[] item);

}
